version: '3.4'

services:
  btdatabaseapplicationappframework:
    image: ${DOCKER_REGISTRY-}btdatabaseapplicationappframework
    build:
      context: .\BTDatabaseApplicationAppFramework
      dockerfile: Dockerfile

     