//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTDatabaseApplicationAppFramework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AtlasDatabaseEntities : DbContext
    {
        public AtlasDatabaseEntities()
            : base("name=AtlasDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DDI_Details> DDI_Details { get; set; }
        public virtual DbSet<DDI_User_Details> DDI_User_Details { get; set; }
        public virtual DbSet<Response_Group_Members> Response_Group_Members { get; set; }
        public virtual DbSet<DDI_Status> DDI_Status { get; set; }
        public virtual DbSet<Response_Grp_MemberTypes> Response_Grp_MemberTypes { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Response_Group> Response_Group { get; set; }
    
        public virtual ObjectResult<TelephoneAvailability_Result> TelephoneAvailability(string dDIStatus)
        {
            var dDIStatusParameter = dDIStatus != null ?
                new ObjectParameter("DDIStatus", dDIStatus) :
                new ObjectParameter("DDIStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TelephoneAvailability_Result>("TelephoneAvailability", dDIStatusParameter);
        }
    }
}
