
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BTDatabaseApplicationAppFramework.Models
{


    public partial class DDI_Status
    {
        public int DDI_Status_ID { get; set; }
        public string DDI_Status_Desc { get; set; }
    }
}
