

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTDatabaseApplicationAppFramework.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Response_Grp_MemberTypes
    {
        public int Response_GrpMemberType_Id { get; set; }
        public string Response_GrpMemberType_Desc { get; set; }
    }
}

